const data = [
  {
    id: 111,
    name: "Pink Rozay",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 50,
    img: "public/img/strains/pinkRozay.png",
  },
  {
    id: 121,
    name: "Gelato",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 30,
    img: "public/img/strains/gelato.jpg",
  },
  {
    id: 123,
    name: "Gorilla Glue",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 30,
    img: "public/img/strains/gorilla.jpg",
  },

  {
    id: 114,
    name: "Pink Rozay",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 50,
    img: "public/img/strains/pinkRozay.png",
  },
  {
    id: 115,
    name: "Gelato",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 30,
    img: "public/img/strains/gelato.jpg",
  },
  {
    id: 116,
    name: "Gorilla Glue",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 30,
    img: "public/img/strains/gorilla.jpg",
  },
  {
    id: 117,
    name: "Pink Rozay",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 50,
    img: "public/img/strains/pinkRozay.png",
  },
  {
    id: 118,
    name: "Gelato",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 30,
    img: "public/img/strains/gelato.jpg",
  },
  {
    id: 119,
    name: "Gorilla Glue",
    type: "Indica",
    type2: "Hybrid",
    weight: "3.5g",
    price: 30,
    img: "public/img/strains/gorilla.jpg",
  },
];

export default data;
